### PR TITLE
Improved sort for Beste (JK Version)

### PR DESCRIPTION
**Pull request by balzer82**
Integrated better sorting function for `Beste`, which rankes crowded parking lots down.

close #113

### CODE REVIEW

**Comment by balzer82** [comment]
Looks like Travis needs VW Build Test

**Comment by kiliankoe** [comment]
Sorry for taking a while. This definitely needs VW powered tests, the swift version is called [Winterkorn](https://github.com/neonichu/Winterkorn) by the way :D

Any chance you could remove `xcuserdata/paul.xcuserdatad` from this PR? I'll gladly merge it in then. You could just go ahead and add everything below `xcuserdata` to the gitignore as well, that's all stuff only relevant to your local project.

**Comment by kiliankoe** [comment]
Due to recent changes I'm going to have to merge this in much more manually anyways, so don't worry about what I wrote earlier^^

**Comment by kiliankoe** [comment]
*merged* in 5a12535c77e98826067fca522d3d2c1f79e6cc35

**Pull request closed without merging**
